name: Build

on:
  workflow_call:
    inputs:
      project-to-build:
        required: true
        type: string
      project-to-test:
        required: false
        type: string
      test-filter:
        required: false
        type: string
        default: TestCategory!=Integration
      coverage-threshold:
        required: false
        type: number
        default: 100

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      OFFICIAL_BUILD: "True"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build "${{inputs.project-to-build}}" --no-restore --configuration Debug

  Test:
    runs-on: ubuntu-latest
    if: inputs.project-to-test != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Test
        run: dotnet test "${{inputs.project-to-test}}" --filter "${{inputs.test-filter}}" /p:CollectCoverage=true /p:Threshold=${{inputs.coverage-threshold}} /p:ThresholdType=line /p:ThresholdStat=total /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$GITHUB_WORKSPACE/coverage.xml

      - name: Generate Test Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.3
        with:
          reports: "coverage.xml"
          targetdir: "coveragereport"
          reporttypes: "HtmlInline;Cobertura;Badges" # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, Html_Dark, Html_Light, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlInline_AzurePipelines_Light, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MarkdownSummary, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
          verbosity: "Info"
          tag: "${{ github.run_number }}_${{ github.run_id }}"
          toolpath: "reportgeneratortool"
        if: always()

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CoverageReport
          path: coveragereport
        if: always()

  Verify:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: PrePack
        run: dotnet pack "${{inputs.project-to-build}}" --configuration Release --output ./unsigned

      - name: Verify Package Metadata
        run: microsoft/digitalworkplace-workflows/scripts/msft-verify.ps1@users/mibir/new-workflows
        shell: pwsh