name: Pack

on:
  workflow_call:
    inputs:
      project-to-pack:
        required: true
        type: string

jobs:
  Pack:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore packages
        run: dotnet restore

      - name: Package project
        run: dotnet pack "${{inputs.project-to-pack}}" --configuration Release --output ./unsigned /p:BuildNumber=${{ github.run_number }} /p:GITHUB_ACTIONS=true

      - name: Verify Package Metadata
        run: |
          $url = "https://raw.githubusercontent.com/NuGet/NuGetGallery/main/src/VerifyMicrosoftPackage/verify.ps1"
          Invoke-WebRequest $url -OutFile verify.ps1
          .\verify.ps1 .\unsigned\*.nupkg
        shell: pwsh

      - name: Upload Unsigned Packages
        uses: actions/upload-artifact@v3
        with:
          name: unsigned
          path: unsigned