name: Pack

on:
  workflow_call:
    inputs:
      project-to-pack:
        required: true
        type: string

jobs:
  Pack:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
        with:
          dotnet-version: 6.0.x

      - name: Restore packages
        run: dotnet restore

      - name: Package project
        run: dotnet pack "${{inputs.project-to-pack}}" --configuration Release --output ./unsigned /p:BuildNumber=${{ github.run_number }} /p:GITHUB_ACTIONS=true

      - name: Verify Package Metadata
        run: |
          $url = "https://raw.githubusercontent.com/NuGet/NuGetGallery/main/src/VerifyMicrosoftPackage/verify.ps1"
          Invoke-WebRequest $url -OutFile verify.ps1
          .\verify.ps1 .\unsigned\*.nupkg
        shell: pwsh

      - name: Upload Unsigned Packages
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: unsigned
          path: unsigned