name: Release

on:
  workflow_call:
    inputs:
      project-to-release:
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  Pack:
    runs-on: ubuntu-latest
    env:
      OFFICIAL_BUILD: 'True'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore packages
        run: dotnet restore

      - name: Build CLI tool
        run: dotnet pack "${{inputs.project-to-release}}" --configuration Release --output ./unsigned

      - name: Upload Unsigned Packages
        uses: actions/upload-artifact@v2
        with:
          name: unsigned
          path: unsigned

  Sign:
    needs: Build
    uses: ./.github/workflows/sign.yml
    secrets:
      client_id: ${{ secrets.AAD_SIGNING_CLIENT_ID }}
      az_creds: ${{ secrets.AZURE_CREDENTIALS }}
      az_sub: ${{ secrets.AZURE_SUBSCRIPTION }}
      storage_name: ${{ secrets.AZURE_STORAGE }}
      container_name: ${{ secrets.AZURE_STORAGE_CONTAINER }}
      vault_name: ${{ secrets.AZURE_VAULT }}
      aad_cert: ${{ secrets.AAD_AUTH_CERT }}
      sign_cert: ${{ secrets.ESRP_SIGNING_CERT }}
      signing_cert_fingerprint: ${{ secrets.SIGNING_CERT_FINGERPRINT }}

  Publish:
    needs: [Build, Sign]
    uses: ./.github/workflows/publish.yml
    secrets:
      api_key: ${{ secrets.NUGET_API_KEY }}