name: Release

on:
  workflow_call:
    inputs:
      project-to-release:
        required: true
        type: string
    secrets:
      client_id:
        required: true
      az_creds:
        required: true
      az_sub:
        required: true
      storage_name:
        required: true
      container_name:
        required: true
      vault_name:
        required: true
      aad_cert:
        required: true
      sign_cert:
        required: true
      signing_cert_fingerprint:
        required: true
      api_key:
        required: true

jobs:
  Pack:
    runs-on: ubuntu-latest
    env:
      OFFICIAL_BUILD: 'True'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore packages
        run: dotnet restore

      - name: Build CLI tool
        run: dotnet pack "${{inputs.project-to-release}}" --configuration Release --output ./unsigned

      - name: Upload Unsigned Packages
        uses: actions/upload-artifact@v2
        with:
          name: unsigned
          path: unsigned

  Sign:
    needs: Build
    uses: ./.github/workflows/sign.yml
    secrets:
      client_id: ${{ secrets.client_id }}
      az_creds: ${{ secrets.az_creds }}
      az_sub: ${{ secrets.az_sub }}
      storage_name: ${{ secrets.storage_name }}
      container_name: ${{ secrets.container_name }}
      vault_name: ${{ secrets.vault_name }}
      aad_cert: ${{ secrets.aad_cert }}
      sign_cert: ${{ secrets.sign_cert }}
      signing_cert_fingerprint: ${{ secrets.signing_cert_fingerprint }}

  Publish:
    needs: [Build, Sign]
    uses: ./.github/workflows/publish.yml
    secrets:
      api_key: ${{ secrets.api_key }}