name: Sign

on:
  workflow_call:
    secrets:
      azure_login_client_id:
        required: true
      aad_tenant_id:
        required: true
      azure_subscription_id:
        required: true
      storage_account_name:
        required: true
      container_name:
        required: true
      key_vault_name:
        required: true
      esrp_aad_client_id:
        required: true
      esrp_aad_auth_cert:
        required: true
      esrp_signing_cert:
        required: true
      esrp_signing_cert_thumbprint:
        required: true

permissions:
  id-token: write

jobs:
  Sign:
    runs-on: windows-latest
    environment: Sign
    steps:
    - name: Download Unsigned Packages
      uses: actions/download-artifact@v3
      with:
        name: unsigned
        path: unsigned

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.azure_login_client_id }}
        tenant-id: ${{ secrets.aad_tenant_id }}
        subscription-id: ${{ secrets.azure_subscription_id }}

    - name: Run Signing Script
      run: |
        $url = "https://raw.githubusercontent.com/microsoft/digitalworkplace-workflows/main/scripts/sign.ps1"
        Invoke-WebRequest $url -OutFile sign.ps1
        .\sign.ps1 ${{ secrets.esrp_aad_client_id }} ${{ github.workspace }} ${{ secrets.azure_subscription_id }} ${{ secrets.storage_account_name }} ${{ secrets.container_name }} ${{ secrets.key_vault_name }} ${{ secrets.esrp_aad_auth_cert }} ${{ secrets.esrp_signing_cert }} ${{ secrets.esrp_signing_cert_thumbprint }}
      shell: pwsh

    - name: Azure logout
      run: az logout
      if: always()

    - name: Upload Signed Packages
      uses: actions/upload-artifact@v3
      with:
        name: signed
        path: signed