name: Sign

on:
  workflow_call:
    secrets:
      azure_login_client_id:
        required: true
      aad_signing_client_id:
        required: true
      aad_tenant_id:
        required: true
      azure_subscription_id:
        required: true
      storage_name:
        required: true
      container_name:
        required: true
      vault_name:
        required: true
      aad_cert:
        required: true
      sign_cert:
        required: true
      signing_cert_fingerprint:
        required: true

permissions:
  id-token: write

jobs:
  Sign:
    runs-on: windows-latest
    environment: sign
    steps:
    - name: Download Unsigned Packages
      uses: actions/download-artifact@v2
      with:
        name: unsigned
        path: unsigned

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.azure_login_client_id }}
        tenant-id: ${{ secrets.aad_tenant_id }}
        subscription-id: ${{ secrets.azure_subscription_id }}

    - name: Run Signing Script
      run: |
        $url = "https://raw.githubusercontent.com/microsoft/digitalworkplace-workflows/main/scripts/sign.ps1"
        Invoke-WebRequest $url -OutFile sign.ps1
        .\sign.ps1 ${{ secrets.aad_signing_client_id }} ${{ github.workspace }} ${{ secrets.azure_subscription_id }} ${{ secrets.storage_name }} ${{ secrets.container_name }} ${{ secrets.vault_name }} ${{ secrets.aad_cert }} ${{ secrets.sign_cert }} ${{ secrets.signing_cert_fingerprint }}
      shell: pwsh

    - name: Azure logout
      run: az logout
      if: always()

    - name: Upload Signed Packages
      uses: actions/upload-artifact@v2
      with:
        name: signed
        path: signed